---
title: "ilex-physcraper-test"
output: rmarkdown::html_document
---

To perform a test of Physcraper functionality, we pruned ~20% of the Gottlieb et al. tree (10 tips) and the corresponding sequences from the alignment, and performed a Physcraper run to test if we would recover the dropped tips:

```
pg_2827_tree6577 <- rotl::get_study_tree(study_id = "pg_2827", tree_id = "tree6577", tip_label = "ott_taxon_name")

```
```{r, echo=TRUE}
outgroup_index <- match(c("Helwingia_chinensis", "Helwingia_japonica"), pg_2827_tree6577$tip.label)
ingroup_tip.label <- pg_2827_tree6577$tip.label[-outgroup_index]
ingroup_ntip <- length(ingroup_tip.label)
ingroup_ntip* 0.8
```
```{r, echo = TRUE}


todrop <- sample(ingroup_tip.label, ingroup_ntip-37)


```

```
physcraper_run.py -s pg_2827 -t tree6577 -o data/pg_2827_tree6577
```

```
physcraper_run.py -s pg_2827 -t tree6577 -a data-raw/alignments/T1281-M2478.nex -as nexus -o data/ilex-remote
```

### Using a local BLAST database

```
physcraper_run.py -s pg_2827 -t tree6577 -a data-raw/alignments/T1281-M2478.nex -as nexus -db local_blast_db -o data/ilex-local
```
