# trenex2pdf
#
# Write nexus tree files to pdf.
#
#' @param treefile A character vector with the name of the nexus or newick file
#' @param studyid TreeBASE study id

trenex2pdf <- function(treefile,
                       treefilesdir = "../data-raw/trees/treebase/S1091/",
                       treepdfsdir = "../data-raw/trees/treebase/S1091-pdf/",
                       height = 7, ...){
  # all treebase trees are in nexus format
  tree <- ape::read.nexus(file= paste0(treefilesdir, "/", treefile))

  outputfile <- paste0(treepdfsdir, gsub(".nex", ".pdf", treefile))
  pdf(file = outputfile, height)
  ape::plot.phylo(ape::ladderize(tree), cex = 0.5, ...)
  graphics::mtext(paste("TreeBASE tree:", gsub(".nex", "", treefile)))
  dev.off()
}

# get_file_names
#
# Write nexus or newick files to pdf or png.
#
#' @param studyid TreeBASE study id
#' @param file_dir Character vector of a directory with one or more tree files

get_file_names <- function(studyid, file_dir = "data-raw/trees/treebase"){
  # dir_original <- getwd()
  print(getwd())
  treefiles <- paste0(studyid, "-treefiles.csv")
  system(paste0("ls ", studyid, " > ", treefiles))
  return(paste0(file_dir, "/", treefiles))
}

# Cummulative sum of tip values for each node/branch down to the root
#
#
#' @param tree a phylo object
#' @param values named numeric character vector with names corresponding to tip labels
#' @author Luna L. Sanchez Reyes
#' @return a vector
#'

sum_tips <- function(tree, values) {
    # tree <- ape::reorder.phylo(tree, "postorder")  # no need to reorder the whole tree
    res <- numeric(max(tree$edge))
    res[1:ape::Ntip(tree)] <- values[match(names(values), tree$tip.label)]
    for (i in ape::postorder(tree))  { # ape postorder doesn't include root
         tmp <- tree$edge[i,1]
         # print(i)
         res[tmp] <- res[tmp] + res[tree$edge[i, 2]]
         # print(res)
   }
   res
}


# Assign tip values to a tree based on OTU information file.
#
#' @param treefile A character vector with the path to the tree you want to plot in newick format.
#' @param otufile A character vector with the path to the OTU information csv file generated by Physcraper
#' @author Emily Jane McTavish
#' @return a list of a phylo object and a vector of tip values
#' @example
#' treefile = 'data/pg_2827_tree6577/run_pg_2827tree6577_run4/RAxML_bestTree.2020-07-31'
#' otufile = 'data/pg_2827_tree6577/outputs_pg_2827tree6577/otu_info_pg_2827tree6577.csv'

get_tip_values <- function(treefile, otufile){

  phytree = ape::read.tree(treefile)

  tip_info = utils::read.csv(otufile, sep = '\t', row.names = 1, stringsAsFactors = FALSE)

  inout <- as.vector(tip_info$X.physcraper.ingroup)
  names(inout) <- rownames(tip_info)

  outgroups = c()
  for (lab in phytree[["tip.label"]]) {
    status = inout[names(inout) == lab]
    if (status == "False")
    {outgroups = c(outgroups, lab)}
  }


  st <- as.vector(tip_info$X.physcraper.status)
  names(st) <- rownames(tip_info)

  spp <- as.vector(tip_info$X.ot.ottTaxonName)
  names(spp) <- rownames(tip_info)


  newtips = c()
  spp_labels = c()
  for (lab in phytree[["tip.label"]]) {
    status = st[names(st) == lab]
    val = grepl("new", status, fixed = TRUE)
    val = 100*as.integer(val)
    names(val) <- lab
    newtips = c(newtips, val)
    tax = spp[names(spp) == lab]
    spp_labels = c(spp_labels, tax)
  }
  return(list(phytree=phytree, newtips=newtips, spp_labels=spp_labels, outgroups=outgroups))

}

# Plot a tree with branches colored according to molecular data, method 1
#
#' @param x A list from get_tip_values
#' @param tip_label A character vector. Can be one of "otu" or "taxon"
#' @param drop_outgroup Boolean
#' @param ladderize_tree Boolean
#' @author Emily Jane McTavish
#' @return a plot
#' @example
#' treefile = 'data/pg_2827_tree6577/run_pg_2827tree6577_run4/RAxML_bestTree.2020-07-31'
#' otufile = 'data/pg_2827_tree6577/outputs_pg_2827tree6577/otu_info_pg_2827tree6577.csv'

plot_branches_method1 <- function(x, tip_label = "otu", drop_outgroup = TRUE, ladderize_tree = TRUE, color = "red", ...){

  phytree <- x$phytree
  if (!inherits(phytree, "phylo"))
    stop("tree should be an object of class \"phylo\".")

  newtips <- x$newtips
  tip_label <- match.arg(tip_label, c("otu", "taxon"))
  if("taxon" %in% tip_label){
  phytree[["tip.label"]] <- x$spp_labels
  names(newtips) <- phytree[["tip.label"]]
  }

  if(drop_outgroup){
    phytree <- ape::drop.tip(phytree, phytree$tip.label[match(x$outgroups, phytree$tip.label)])
    newtips <- newtips[!names(newtips) %in% x$outgroups]
  }

  if(ladderize_tree){
    phytree <- ape::ladderize(phytree)
    ii <- match(phytree$tip.label, names(newtips))
    newtips <- newtips[ii]
  }
  tip_color <- ifelse(newtips == 0, "black", color)
  phytools::plotBranchbyTrait(tree = phytree,
                              x = newtips,
                              mode = "tips",
                              legend=TRUE,
                              show.tip.label = TRUE,
                              palette=colorRampPalette(c("black", color)),
                              tip.color=tip_color,
                              ...)
}

#' Get a plot of a tree with tips and branches colored following a tip value.
#'
#' @inheritParams get_tip_values
#'
#' @return a plot

plot_branches <- function(treefile, otufile, ...){
  x <- get_tip_values(treefile, otufile)
  plot_branches_method1(x, ...)
  
}

# phytools::plotBranchbyTrait(tree = phytree,
#                               x = newtips,
#                               mode = "tips",
#                               legend=FALSE,
#                               show.tip.label = FALSE,
#                               palette=colorRampPalette(c("black", "red")),
#                               type='phylogram',
#                               edge.width = 1,
#                               show.tip.label = TRUE,
#                               label.offset= 0,
#                             align.tip.label = TRUE)

## set working directory to path to https://github.com/McTavishLab/physcraper_example

#treefile = 'data/pg_2827_tree6577/run_pg_2827tree6577_run4/RAxML_bestTree.2020-07-31'
#otufile = 'data/pg_2827_tree6577/outputs_pg_2827tree6577/otu_info_pg_2827tree6577.csv'

#treefile = 'pg_55_local_new/outputs_pg_55tree5864_ndhf/physcraper_pg_55tree5864_ndhf.tre'
#otufile = 'pg_55_local_new/outputs_pg_55tree5864_ndhf/otu_info_pg_55tree5864_ndhf.csv'


#treefile = 'ot_350/outputs_ot_350Tr53297/physcraper_ot_350Tr53297.tre'
#otufile = 'ot_350/outputs_ot_350Tr53297/otu_info_ot_350Tr53297.csv'
